# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-29 14:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PeopleCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_join', models.DateField(default=datetime.date.today)),
                ('time_join', models.TimeField()),
                ('head_count', models.IntegerField()),
                ('people_count', models.IntegerField()),
            ],
            options={
                'ordering': ('-date_join', '-time_join'),
            },
        ),
    ]
